-- Индексы
BEGIN TRANSACTION
CREATE UNIQUE NONCLUSTERED INDEX Number_Group ON dbo.Groups
	(
	Number
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX Number_SubGroups ON dbo.SubGroups
	(
	Number
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX Number_Sections ON dbo.Sections
	(
	Number
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX Number_Sections ON dbo.SubSections
	(
	Number
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX CodeMTR_Products ON dbo.Products
	(
	CodeMTR
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX Description_Products ON dbo.Products
	(
	ShortDescription
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE UNIQUE NONCLUSTERED INDEX Product_Properties ON dbo.Properties
	(
	ProductID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

CREATE NONCLUSTERED INDEX PropertyName_Properties ON dbo.Properties
	(
	PropertyName
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

COMMIT
GO

-- Первичные ключи
BEGIN TRANSACTION
ALTER TABLE dbo.Groups ADD CONSTRAINT
	PK_Group PRIMARY KEY CLUSTERED 
	(
	GrourID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo.SubGroups ADD CONSTRAINT
	PK_SubGroups PRIMARY KEY CLUSTERED 
	(
	SubGroupID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo.Sections ADD CONSTRAINT
	PK_Sections PRIMARY KEY CLUSTERED 
	(
	SectionID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo.SubSections ADD CONSTRAINT
	PK_SubSections PRIMARY KEY CLUSTERED 
	(
	SubSectionID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo.Products ADD CONSTRAINT
	PK_Products PRIMARY KEY CLUSTERED 
	(
	ProductID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo.Properties ADD CONSTRAINT
	PK_Properties PRIMARY KEY CLUSTERED 
	(
	PropertyID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo.Derevatives ADD CONSTRAINT
	PK_Derevatives PRIMARY KEY CLUSTERED 
	(
	DerevativeID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo.ValueTypes ADD CONSTRAINT
	PK_ValueTypes PRIMARY KEY CLUSTERED 
	(
	ValieTypeID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

ALTER TABLE dbo.CodeListProperties ADD CONSTRAINT
	PK_CodeListProperties PRIMARY KEY CLUSTERED 
	(
	CodeListPropertyID
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

COMMIT
GO

-- Внешние ключи
BEGIN TRANSACTION
ALTER TABLE dbo.SubSections SET (LOCK_ESCALATION = TABLE)
ALTER TABLE dbo.Products ADD CONSTRAINT
	FK_Products_SubSections FOREIGN KEY
	(
	SubSectionID
	) REFERENCES dbo.SubSections
	(
	SubSectionID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
ALTER TABLE dbo.Products SET (LOCK_ESCALATION = TABLE)

ALTER TABLE dbo.Sections SET (LOCK_ESCALATION = TABLE)
ALTER TABLE dbo.SubSections ADD CONSTRAINT
	FK_SubSections_Sections FOREIGN KEY
	(
	SectionID
	) REFERENCES dbo.Sections
	(
	SectionID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
ALTER TABLE dbo.SubSections SET (LOCK_ESCALATION = TABLE)

ALTER TABLE dbo.SubGroups SET (LOCK_ESCALATION = TABLE)
ALTER TABLE dbo.Sections ADD CONSTRAINT
	FK_Sections_SubGroups FOREIGN KEY
	(
	SubGroupID
	) REFERENCES dbo.SubGroups
	(
	SubGroupID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
ALTER TABLE dbo.Sections SET (LOCK_ESCALATION = TABLE)

ALTER TABLE dbo.Groups SET (LOCK_ESCALATION = TABLE)
ALTER TABLE dbo.SubGroups ADD CONSTRAINT
	FK_SubGroups_Groups FOREIGN KEY
	(
	GroupID
	) REFERENCES dbo.Groups
	(
	GrourID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
ALTER TABLE dbo.SubGroups SET (LOCK_ESCALATION = TABLE)
COMMIT
GO

-- Полнотекстовый каталог и индексы
CREATE FULLTEXT CATALOG [MTRDescriptions] WITH ACCENT_SENSITIVITY = ON
AS DEFAULT
AUTHORIZATION dbo
GO
CREATE FULLTEXT INDEX ON [dbo].[Products]([Description])
KEY INDEX ProductID ON ([MTRDescriptions])
WITH (CHANGE_TRACKING AUTO)
GO
CREATE FULLTEXT INDEX ON [dbo].[Products]([ShortDescription])
KEY INDEX ProductID ON ([MTRDescriptions])
WITH (CHANGE_TRACKING AUTO)
GO
CREATE FULLTEXT INDEX ON [dbo].[Products]([LongDescription])
KEY INDEX ProductID ON ([MTRDescriptions])
WITH (CHANGE_TRACKING AUTO)
GO